### ISSUE TITLE
Optional field with default generates required field

### ISSUE THREAD

**Issue by Brenndoerfer** [chrishoermann/zod-prisma-types#103]
When the Prisma model defines an optional value, for example:

`max_ping_timeout Int?` then the Zod schema will be `z.number().int().nullable(),`

However, if you define a default for the optional field, e.g. `max_ping_timeout Int? @default(5)`, the generated zod schema is `z.number().int()`, not nullable. 

I believe this is not the intended behavior, as a default on an optional field is a sensible default, not a requirement. 

I am on `"zod-prisma-types": "^2.0.12",`

**Comment by chrishoermann** [comment]
@Brenndoerfer actutally you're only kind of right. :wink: 
The generator only reflects the types from prisma's `index.d.ts`.

## CreateInput type
So let's say we have the following model:

```prisma
model WithDefault {
  id        Int    @id @default(autoincrement())
  default   String @default("default")
  noDefault String
}
```

According to this model the `default` field should be optional when creating an entry . If we look in the `index.d.ts` the `createInputType` does reflect this:

```ts
export type WithDefaultCreateInput = {
  default?: string
  noDefault: string
}
```

The corresponding zod schema also reflects this optional field

```ts
export const WithDefaultCreateInputSchema: z.ZodType<Prisma.WithDefaultCreateInput> =
  z
    .object({
      default: z.string().optional(),
      noDefault: z.string(),
    })
    .strict();
```

## Model type
This is different in the model `type`. In the `index.d.ts` the type of the model looks like this:

```ts
export type WithDefault = {
  id: number
  default: string
  noDefault: string
}
```

and the schema also reflects this:

```ts
export const WithDefaultSchema = z.object({
  id: z.number().int(),
  default: z.string(),
  noDefault: z.string(),
})
```

so here the `default` field is not optional. This is because the model type is the one that is used when retrieving an element from the database and there the `default` field should never be `undefined` or `null`. 

## Solutions

So if you just need the type when creating an element, I'd suggest to use the corresponding `CreateInputType`.
If you need a field of the model type to be optional you'd have to use a workaround like this:

```ts
const PickedType = WithDefaultSchema.omit({
  default: true,
}).merge(
  z.object({
    default: z.string().optional(),
  }),
);

// The type would be:

type PickedType = {
    default?: string | undefined;
    id: number;
    noDefault: string;
}
```

Hope this helps.

**Comment by Brenndoerfer** [comment]
Thanks for the explanation. Interestingly, I noticed that I had `createOptionalDefaultValuesTypes` already set to true. Will debug a bit more, ant report back soon. Thanks for the elaborate response!
