### ISSUE TITLE
[BUG] extendedDMMFModel_1.ExtendedDMMFModelClass is not a constructor after upgrade from 2.7.9 to 2.8.1

### ISSUE THREAD

**Issue by EdwardDrapkin** [chrishoermann/zod-prisma-types#202]
**Describe the bug**
Package is broken with error after upgrading:

```

Prisma schema loaded from libs/api-contracts/database/schema.legacy.prisma
Error:
extendedDMMFModel_1.ExtendedDMMFModelClass is not a constructor
```

**Package versions (please complete the following information):**
 - zod: latest
 - prisma: latest

**Additional context**

There is no exported `ExtendedDMMFModelClass` from the generated `node_modules/zod-prisma-types/dist/classes/extendedDMMFModel.js`

**Comment by chrishoermann** [comment]
@EdwardDrapkin thanks for reporting the issue. Can you please try and delete the node modules folder and reinstall all dependencies. The `ExtendendDMMFModelClass` was moved to the `index.js` in the folder. So it seems the generator looks in the wrong place.

please also be aware that the latest zod version still has issues with the generated zod schemas. So please use zod version 3.21.1 until the issue is resolved.
