### ISSUE TITLE
Expose "Unchecked" (and other) zod Objects as zod Objects

### ISSUE THREAD

**Issue by nbibler** [chrishoermann/zod-prisma-types#210]
[zod Objects](https://github.com/colinhacks/zod#objects) allow for object extension and manipulation via utilities like [.pick()/omit()](https://github.com/colinhacks/zod#pickomit) and [.shape()](https://github.com/colinhacks/zod#shape), among many others. This library currently generates several zod Objects, but it tends to expose them as a zod Type to the application. zod Types are _far_ more limited in functionality than zod Objects.

```typescript
export const TableNameUncheckedCreateInputSchema: z.ZodType<Prisma.TableNameUncheckedCreateInput> =
  z
    .object({
      id: z.string(),
      secret: z.string(),
    })
    .strict()
```

I assume it was primarily done this way to ensure that the generated zod Object is compatible with the Prisma-generated type. But, there's a better way to do that since TypeScript 4.9+ _and_ expose the actual zod Object to the application, via [`satisfies`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator):

```typescript
export const TableNameUncheckedCreateInputSchema =
  z
    .object({
      id: z.string(),
      secret: z.string(),
    })
    .strict() satisfies z.ZodType<Prisma.TableNameUncheckedCreateInput>
```

It would be hugely beneficial to expose the zod Objects directly to the application. Among other things, this would allow developers to more easily generate derived or extended Objects/schemas. This is useful, for example, to limit HTML form inputs to a subset of properties:

```typescript
export const MyFormSchema = TableNameUncheckedCreateInputSchema.pick({ id: true });
// This is a Schema that disallows the `secret` to be passed, for instance.
```

**Comment by chrishoermann** [comment]
@nbibler thanks for the idea but sadly this is not possbile since the prisma types are heavily recurseive and zod needs this type annotation as a type hint to work correctly as [stated in the zod docs](https://zod.dev/?id=recursive-types)

As you mentioned it would be very beneficial for DX but here's an example type error for a recursive schema when using `satisfied`:

![image](https://github.com/chrishoermann/zod-prisma-types/assets/53531653/6845d0a6-ffd1-4a4a-bf59-cb3b41c1d463)
