### ISSUE TITLE
Split generated output in file by model

### ISSUE THREAD

**Issue by kachar** [chrishoermann/zod-prisma-types#43]
Is there an idea for splitting the generator output into dedicated files per model as `zod-prisma` does?

At the moment the generated output of my schema results in a 13k rows `index.ts` file which destroys the performance of the IDE and computer in general.

Also, the Vercel builds are failing after 45 minutes of type checking

![image](https://user-images.githubusercontent.com/893608/209458299-7aaf9c01-f79f-4b6b-9fee-934b1cf02bd3.png)
![image](https://user-images.githubusercontent.com/893608/209458310-cf129f3f-12bc-4435-b7fe-61750de6668c.png)

## Sample

- `PostSchema` > `./zod/post.ts`
- `AuthorSchema` > `./zod/author.ts`

A nice addition might be a barrel file `./zod/index.ts` that exports all generated models:

```ts
export * from "./post"
export * from "./author"
````

**Comment by chrishoermann** [comment]
@kachar I initially decided against a multiple file approach because it makes the handling of custom imports much easier and the generator itself is easier from a code prespective (no imports from related models, enums, inputTypes and so on need to be handled, no index files need to be created, ...). 

In the process of writing the generator I also realized, that because of the structure of the `dmmf` (where all the information about the models, enums, inputTypes, ... and their relation between each other is stored) an approach that colocates all schemas of a model in one file would make the whole generator much more complex with no guarantee that it will lead to a satisfying and fast solution programming wise.

An option that is possible and that `zod-prisma` is using is, that each generated schema (inputType, argType, enum, ...) has a unique file. So then hundreds or thousands of files (depending on the size of your `prisma schema`) need to be deleted and recreated on each run of the generator which slows the process of generation down. 

I also realized in my own tests that IDE performance can be a bit of a show stopper on big `prisma schemas` especially after the generator has run. I believe this is because the typescript server needs to load all the type information of the generated schemas which can take a while. As far as I experienced it, this also happens on a multi file approach but just in the background. When using `zod-prisma` the generated types often needed minutes to show up in the autocomplete which I think is because typescript needs to load a whole lot of new types.

I don't know if this is more of  a zod thing because TS needs to infer a shitload of new of types or if this is a typescript thing because in the blink of an eye hundreds or thousands of types are created and the TS server is kind of overwhelmed. Maybe someone with more insight in both can shed some light on this. I also don't know if a barrel file would solve the issue because in any case the types need to be loaded and, to my understanding, it shoud not matter if they are split into multiple files or if they are all located in one file. Again if someone has some deeper insight here, any advice is welcome.

But to come back to your suggestion  I currently don't plan on implementing a multi file option because it adds complexity and would require a major refactor of some parts of the code and also in the next few month I'll be a bit short on time and don't know how much of it I can invest in open source stuff.

**Comment by kachar** [comment]
That's too many fair points indeed, I do agree it's a new course for the whole lib. 

I started the thread since I couldn't find information on why this design decision has been taken and initially thought that it was not yet in the roadmap. Thanks for giving details info and thoughts on the topic :thought_balloon: Really valuable! Indeed the TS performance might be problematic even if the types are split across files.

Maybe you might add a few bullets in the README so other people may grasp that knowledge upfront.

**Comment by chrishoermann** [comment]
closing in favor of #48
