### ISSUE TITLE
How to use Decimal with tRPC?

### ISSUE THREAD

**Issue by Paul-Meltzer** [chrishoermann/zod-prisma-types#56]
Thank you, for this nice lib. It seems to be exactly what I was looking for, to auto generate the validations for my tRPC routes.

Sadly, I'm stuck with one issue since last week: Decimals

If I hand over the number as a `Prisma.Decimal`, I receive the following error:
```
TRPCClientError: [
  {
    "code": "unrecognized_keys",
    "keys": [
      "constructor",
      "s",
      "e",
      "d",
      ...,
        "valueOf"
    ],
    "path": [
      "data",
      "discountPrice"
    ],
    "message": "Unrecognized key(s) in object: 'constructor', 's', 'e', 'd',..., 'valueOf'"
  }
]
```

If I hand over the number as a `number`, I receive the following error:
```
TRPCClientError: [
  {
    "code": "custom",
    "message": "Must be a Decimal",
    "path": [
      "data",
      "discountPrice"
    ]
  }
]
```

Also, the value as a `string` is not accepted, and I also tested the option `useInstanceOfForDecimal` without success.

My setup reduced to the minimum and all dependencies up to date:
Prisma schema:
```
generator client {
  provider = "prisma-client-js"
}

generator zod {
  provider       = "zod-prisma-types"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Deal {
  id                    String      @id @default(cuid())
  discountPrice         Decimal?    @db.Decimal(9,2)
}
```

tRPC route:
```
export const dealRouter = router({
    updateDeal: protectedAdminProcedure.input(DealUpdateArgsSchema).mutation(({ input }) => prisma.deal.update(input)),
});
```

Excerpts of the generated Zod schema:
```
export const DealUpdateArgsSchema: z.ZodType<PrismaClient.Prisma.DealUpdateArgs> = z.object({
  select: DealSelectSchema.optional(),
  include: DealIncludeSchema.optional(),
  data: z.union([DealUpdateInputSchema, DealUncheckedUpdateInputSchema]),
  where: DealWhereUniqueInputSchema,
}).strict();
export const DealUpdateInputSchema: z.ZodType<PrismaClient.Prisma.DealUpdateInput> = z.object({
  id: z.union([z.string().cuid(), z.lazy(() => StringFieldUpdateOperationsInputSchema)]).optional(),
  discountPrice: z.union([z.number().refine((v) => PrismaClient.Prisma.Decimal.isDecimal(v), { message: 'Must be a Decimal' }), z.lazy(() => NullableDecimalFieldUpdateOperationsInputSchema)]).optional().nullable(), 
}).strict();
export const DealUncheckedUpdateInputSchema: z.ZodType<PrismaClient.Prisma.DealUncheckedUpdateInput> = z.object({
  id: z.union([z.string().cuid(), z.lazy(() => StringFieldUpdateOperationsInputSchema)]).optional(),
  discountPrice: z.union([z.number().refine((v) => PrismaClient.Prisma.Decimal.isDecimal(v), { message: 'Must be a Decimal' }), z.lazy(() => NullableDecimalFieldUpdateOperationsInputSchema)]).optional().nullable(),
}).strict();
```

How should I pass the decimal to validate successful?

**Comment by chrishoermann** [comment]
Hey @Paul-Meltzer, thanks for the report and glad you like the library. I looked into it and it was a mistake on my side that should be fixed in  `v1.6.4`.

I actually did not test the decimal validation in a real world example because I haven't used decimal in my application yet and I obviously was too lazy to write a test although it wasn't that much work :see_no_evil:. 
But now the decimal field accepts a `string`, a `number` or a `Decimal` object. If a wrong type is provided a validation error is thrown by zod. In my tests it worked but can you please report back if it also works in your situation?

**Comment by Paul-Meltzer** [comment]
Hi @chrishoermann, thank you very much for the fast reply and changes. 

I tested it, but got some problems:

1. The `isValidDecimalInput` is used but not defined in the generated file, or should it be imported from somewhere?
2. The new check is only defined in the schema itself but not in all the other variants like `XXXUpdateInputSchema` or `XXXWhereInputSchema`

But I also copied and tested the new Zod validation, and it worked on my side 👍

**Comment by chrishoermann** [comment]
@Paul-Meltzer sorry that it took some time but as of version `v1.6.7` all decimal types that are accepted by prisma (`string | number | Prisma.Decimal | DecimalJsLike`) should also work in the generated decimal schema.

I initally forgot to mention that the validation in `v1.6.4` only worked on the Model schemas because I had some issues getting the type right in some of the input types but this should also work as expected now.

**Comment by Paul-Meltzer** [comment]
Great work and thanks a lot @chrishoermann!

Now it is working like expected. 🎉
