### ISSUE TITLE
Generated output using a schema that has no definition

### ISSUE THREAD

**Issue by Red-Maximus** [chrishoermann/zod-prisma-types#59]
This library has saved me a ton of time but I am having one issue that is causing compile errors for me. In the Zod output, one of the extra Prisma types is referencing a schema that does not exist.

The model definition in `schema.prisma`

```
model PrismaWorkerVerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
  @@map("WorkerVerificationTokens")
}
```

The output schema definition in `generated/zod/index.ts`

```
export const PrismaWorkerVerificationTokenSchema = z.object({
  identifier: z.string(),
  token: z.string(),
  expires: z.date(),
});
```

The error lives here, in the interpretation of the extra Prisma types

```
export const PrismaWorkerVerificationTokenFindFirstArgsSchema: z.ZodType<PrismaClient.Prisma.PrismaWorkerVerificationTokenFindFirstArgs> = z.object({
...
  include: PrismaWorkerVerificationTokenIncludeSchema.optional(), // <--- This does not exist
...
}).strict();
```

Please let me know if this is user error but `PrismaWorkerVerificationTokenIncludeSchema` is not defined anywhere in the Zod output file or the standard Prisma-generated `index.d.ts`. There are 11 instances where it is referenced in the Zod output. I believe it is correct that there is not an `Include` type for this schema because the original definition has no relations and thus would not have anything to include.

**Comment by chrishoermann** [comment]
Hey @Red-Maximus that is definitly a bug because the include schema should only be generated when a relation to another model is present.

I'll look into this.

**Comment by chrishoermann** [comment]
@Red-Maximus I tried the model you shared and for me it does not generate the `include` option.
Which version of the generator and which database connector in the prisma schema  are you using?

**Comment by Red-Maximus** [comment]
Thanks for looking into this! I'm on version 1.6.7 and this is with a Postgres DB.

**Comment by Red-Maximus** [comment]
@chrishoermann Just as a follow up, I updated to 1.6.8 and the same issue persists.

To anyone who may need it, the simple workaround is just defining the unnecessary type as an empty zod object since it should never be used anyway. Obviously this gets removed after each `prisma generate` but it works well enough. In my case it's the below:

`export const PrismaWorkerVerificationTokenIncludeSchema: z.ZodType<any> = z.object({}).strict();`

**Comment by Paul-Meltzer** [comment]
I can confirm this bug in 1.6.8 with a MySQL.

In my case, I created a simple view in the Prisma schema:
```
view StatisticActiveUsers {
  date                  DateTime    @unique @db.Date
  count                 Int
}
```
In the generated file are many spots in `...ArgsSchema`s where `StatisticActiveUsersIncludeSchema` is used, but no definition.

**Comment by chrishoermann** [comment]
@Red-Maximus, @Paul-Meltzer can you please try version `2.0.0-beta-2` and check if the bug still exists. I refined the the checks when an include schema should be created to support mongoDb and maybe this solves your issues too. Please let me know if it does not.

npm:

```bash
npm install zod-prisma-types@2.0.0-beta.2
```

yarn:

```bash
yarn add zod-prisma-types@2.0.0-beta.2
```

pnpm:

```bash
pnpm add zod-prisma-types@2.0.0-beta.2
```

**Comment by Paul-Meltzer** [comment]
@chrishoermann thank you for the fast reply. 

And I'm sorry, but I tested it with 2.0.0-beta.2 and have still the same issue.

**Comment by chrishoermann** [comment]
@Paul-Meltzer that's wired. Can you check if the include type exists in your prisma `index.d.ts` file? I need to narrow down if the issue is that the include schema is not generated or that the include field is added on the arg type but shouldn't. 

Would it also be possible to share a complete schema with prisma client and generator config so I can try to replicate the issue on my end.

**Comment by chrishoermann** [comment]
@Paul-Meltzer This is a strange issue.  I can't reproduce it, not in my dev environment nor in a new project? 

The thing with the include and select fields is that they are not directly included in the `dmmf.schema` information. So I need to link the information from `dmmf.datamodel` to the information in `dmmf.schema` by checking if the type in `schema` includes the name of the type in `datamodel`. When this link is established I check if the type in `datamodel` has relation fields and, if so, add the `includeSchema`.

This is the only section of the code that comes to my ming where something can go wrong and the types are not linked correctly. The linked model can be `undefined` by definition because in the dmmf info a lot of types have no matching model type and are not used for generating the schemas).

Can you please try version `2.0.0-beta.5`? I refined the checks for the include field a bit - maybe this fixes the issue.

**Comment by Paul-Meltzer** [comment]
@chrishoermann thanks for your quick reply and trying to reproduce it.

I also created a new project and couldn't reproduce. That made me play around with the names. If my view ends with the name of an existing table with relations, I'm getting the includes on the args schemas.

This works fine in my case:
```
view TestView {
  date                  DateTime    @unique @db.Date
  count                 Int
}
```

on the other hand, this will lead to this bug, because I have a table called `User` with relations:
```
view TestViewUser {
  date                  DateTime    @unique @db.Date
  count                 Int
}
```
or
```
view TestViewUsers {
  date                  DateTime    @unique @db.Date
  count                 Int
}
```

Maybe the bug is in the check, if the type in `schema` includes the name of the type in `datamodel`!?

**Comment by Paul-Meltzer** [comment]
@chrishoermann great, this did the trick 🎉 

Thank you for the fast fix 👏
