### ISSUE TITLE
WhereUniqueInputSchema validation behaviour

### ISSUE THREAD

**Issue by binary-birthday** [chrishoermann/zod-prisma-types#68]
I have a User model with two unique fields, id and phoneNumber.

When validating the input using the UserWhereUniqueInputSchema, validation succeeds in the scenario where:

```
phoneNumber = undefined

UserWhereUniqueInputSchema.parse({
      phoneNumber,
});
```

I would expect that validating using the WhereUniqueInputSchema should only succeed if **at least one** of the required unique fields is a valid input.

**Comment by chrishoermann** [comment]
@binary-birthday Since the generator just takes the information that is present in the `prisma dmmf` it creates the schemas according to the prisma types. In these types all unique keys are optional. 

```prisma
model User {
  id         String      @id @default(cuid()) 
  email      String      @unique 
  //...rest
}
```

```ts

// Type in prisma index.d.ts

  export type UserWhereUniqueInput = {
    id?: string
    email?: string
  }

// created schema

export const UserWhereUniqueInputSchema: z.ZodType<Prisma.UserWhereUniqueInput> =
  z
    .object({
      id: z.string().optional(),
      email: z.string().optional(),
    })
    .strict();

export default UserWhereUniqueInputSchema;


```

So I think currenly you need to check if the fields are undefined before hitting the schema. Another way could be to add a custom refine to the `Input schema` like 

```ts
// I'm sure this check can be refined a bit :)
UserWhereUniqueInputSchema.refine((data) => {
  return Object.entries(data).some(([_key, value]) => {
    return value !== undefined;
  });
});
```

This is something that could also be generated automatically by the generator, since all the information should be there, but  I would suggest one of the manual options from above until I can look into this in more detail.

**Comment by chrishoermann** [comment]
I couldn't get it off my mind so I implemented it straight away. Should work now as you described it in the latest version.

**Comment by binary-birthday** [comment]
Oh awesome. I'll check it out now. For a workaround I thinking about using: 

```
UserSchema.pick({ phoneNumber: true}).parse({phoneNumber})
```

But this will be much better.

**Comment by chrishoermann** [comment]
closing since it's now implemented

**Comment by binary-birthday** [comment]
@chrishoermann I've encountered an issue with this feature:

when `UserWhereUniqueInputSchema` is used in a `connectOrCreate` block the original behavior is the expected behavior and I think it makes this a bug rather than a feature. 

I apologise for not  recognising this earlier.

**Comment by chrishoermann** [comment]
Thanks for pointing this out and no problem @binary-birthday. I'll revert back to the previous implementation in the next release.
