### ISSUE TITLE
custom validation does not propagate to WhereUniqueInputSchema

### ISSUE THREAD

**Issue by binary-birthday** [chrishoermann/zod-prisma-types#75]
When adding a custom validation rule such as  
```
/// @zod.custom.use(z.string().refine(val => isMobilePhone(val), "Must be a valid Phone Number"))
```
on a unique field the custom validation rule is not implemented in the ModelWhereUniqueInputSchema block

**Comment by chrishoermann** [comment]
@binary-birthday Sorry my bad, I removed this when implementing the multifile approach because I haven't found a clean way of handling custom imports with this feature and I totally forgot to enable it again. 

The thing is, if I add all custom imports to the file of the "WhereUniqueInputSchema" it is possible that they will be unused when the field where the custom import is used is not in this schema. This can be annoying when using eslint `no-unused-vars`. I'll see how I can fix this. Maybe if I add an option to specifically enable it and point out that the user needs to run a linter to remove all unesed imports?

**Comment by chrishoermann** [comment]
@binary-birthday for now I added the `whereUniqueInput` validation when using a single generated file. When using multifile mode you need to opt in to generate validation. See [docs](https://github.com/chrishoermann/zod-prisma-types#validatewhereuniqueinput). I chose this approach so people are aware that they need to take care of unused imports manually.

In the future I thought about adding the custom imports directly on the field level like 

```prisma
model MyModel {
  myField String ///@zod.string.[...validators].import("import package from "package")
}
```

this way I could easily determine if the import needs to be added for `whereUniqueInput` fields.

but for now please use the method described above.

**Comment by chrishoermann** [comment]
closing since a way to add validator is implemented

**Comment by binary-birthday** [comment]
Thanks @chrishoermann I'm using a single file and not the multifile so this will work for me.
