### ISSUE TITLE
Issue: Related Views

### ISSUE THREAD

**Issue by luke-cbs** [chrishoermann/zod-prisma-types#77]
# Issue

I have encountered a possible bug or case:

```ts
view UsersWithRole {
  id                  String              @unique
  username            String
  fullName            String
  employeeNumber      Int?
  contactNumber       Int?
  role                UserRoles
  restaurantWithUsers RestaurantWithUsers @relation(fields: [restaurantId], references: [id])
  restaurantId        String
}

view RestaurantWithUsers {
  id                String          @unique
  ownerID           String
  name              String
  address           String?
  contactNumber     Int?
  tableCapacity     Int
  usedTableCapacity Int
  users             UsersWithRole[]
  createdAt         DateTime
  updatedAt         DateTime
}
```

So here I have two views. Both of these work perfectly fine when called and return the expected data. However the generated schema looks as follows for RestaurantWithUsers:

```ts
export const RestaurantWithUsersSchema = z.object({
  id: z.string(),
  ownerID: z.string(),
  name: z.string(),
  address: z.string().nullable(),
  contactNumber: z.number().int().nullable(),
  tableCapacity: z.number().int(),
  usedTableCapacity: z.number().int(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
})
```

I swapped the ` users  UsersWithRole[]` to ` users  string[]` and this generated perfectly fine. So only seems to be an issue when referencing another view.

Not sure if this is possible to account for?

**Comment by chrishoermann** [comment]
Hey @luke-cbs, I think you need to set the `createRelationValueTypes` option to true then a separate schema with all relations will be generated. I chose to generate a separate schema because when using relations the `z.ZodType<>` annotation needs to be used and then you loose the ability to use certain methods like `.pick`, `.omit`, etc.

you can find more in [the docs](https://github.com/chrishoermann/zod-prisma-types#createrelationvaluestypes)

**Comment by chrishoermann** [comment]
Closing since I think this should be resolved with the answer above
